# Generated by Django 5.2.5 on 2025-09-01 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trading_app', '0002_herosection_heroavatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteconfig',
            name='site_name',
        ),
    ]
