# Generated by Django 5.2.5 on 2025-09-02 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading_app', '0003_remove_siteconfig_site_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='HighlightSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(verbose_name='Highlight Number')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Title (optional)')),
                ('content', models.TextField(verbose_name='Description')),
                ('image', models.ImageField(upload_to='highlights/', verbose_name='Section Image')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Display Order')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
