# Generated by Django 5.2.5 on 2025-09-02 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading_app', '0004_highlightsection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='highlightsection',
            name='image',
        ),
        migrations.AddField(
            model_name='highlightsection',
            name='center_image',
            field=models.ImageField(blank=True, null=True, upload_to='highlights/', verbose_name='Centered top image'),
        ),
        migrations.AddField(
            model_name='highlightsection',
            name='paragraph_left',
            field=models.TextField(blank=True, verbose_name='Bottom left paragraph'),
        ),
        migrations.AddField(
            model_name='highlightsection',
            name='paragraph_right',
            field=models.TextField(blank=True, verbose_name='Bottom right paragraph'),
        ),
        migrations.AddField(
            model_name='highlightsection',
            name='right_image',
            field=models.ImageField(blank=True, null=True, upload_to='highlights/', verbose_name='Right column image'),
        ),
        migrations.AlterField(
            model_name='highlightsection',
            name='content',
            field=models.TextField(verbose_name='Description (top row left column)'),
        ),
    ]
