# Generated by Django 5.2.5 on 2025-09-02 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading_app', '0005_remove_highlightsection_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='highlightsection',
            options={},
        ),
        migrations.RemoveField(
            model_name='highlightsection',
            name='number',
        ),
        migrations.RemoveField(
            model_name='highlightsection',
            name='order',
        ),
        migrations.RemoveField(
            model_name='highlightsection',
            name='title',
        ),
        migrations.AlterField(
            model_name='highlightsection',
            name='center_image',
            field=models.ImageField(blank=True, null=True, upload_to='highlights/', verbose_name='Top center image'),
        ),
        migrations.AlterField(
            model_name='highlightsection',
            name='content',
            field=models.TextField(verbose_name='Top description'),
        ),
    ]
