# Generated by Django 5.2.5 on 2025-09-02 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading_app', '0006_alter_highlightsection_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Register', max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='register/')),
            ],
            options={
                'verbose_name': 'Register Page',
                'verbose_name_plural': 'Register Page',
            },
        ),
    ]
