# Generated by Django 5.2.5 on 2025-09-02 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading_app', '0007_registerpage'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Login', max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='login/')),
            ],
            options={
                'verbose_name': 'Login Page',
                'verbose_name_plural': 'Login Page',
            },
        ),
    ]
