# Generated by Django 5.2.5 on 2025-09-02 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading_app', '0008_loginpage'),
    ]

    operations = [
        migrations.CreateModel(
            name='HowItWorksStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon', models.ImageField(upload_to='howitworks/')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
