# Generated by Django 5.2.5 on 2025-09-02 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading_app', '0009_howitworksstep'),
    ]

    operations = [
        migrations.CreateModel(
            name='PracticeSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(verbose_name='Step Number')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('highlight', models.BooleanField(default=False, verbose_name='Highlight This Card?')),
                ('button_text', models.CharField(default='Learn More', max_length=50, verbose_name='Button Text')),
                ('button_link', models.URLField(blank=True, verbose_name='Button Link')),
            ],
            options={
                'ordering': ['number'],
            },
        ),
    ]
