# Generated by Django 5.2.5 on 2025-09-02 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading_app', '0010_practicesection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='practicesection',
            name='button_link',
            field=models.URLField(blank=True, null=True, verbose_name='Button Link'),
        ),
        migrations.AlterField(
            model_name='practicesection',
            name='button_text',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Button Text'),
        ),
        migrations.AlterField(
            model_name='practicesection',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
    ]
