# Generated by Django 5.2.5 on 2025-09-02 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading_app', '0011_alter_practicesection_button_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='practicesection',
            name='button_link',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Button Link'),
        ),
    ]
