# Generated by Django 5.2.5 on 2025-09-03 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading_app', '0014_aboutsection_feature'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutsection',
            options={},
        ),
        migrations.AlterField(
            model_name='aboutsection',
            name='body',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aboutsection',
            name='kind',
            field=models.CharField(choices=[('hero', 'Hero'), ('who', 'Who We Are'), ('mission', 'Mission'), ('vision', 'Vision'), ('values', 'Core Values')], max_length=20),
        ),
        migrations.AlterField(
            model_name='aboutsection',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='aboutsection',
            name='subtitle',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.CreateModel(
            name='AboutFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='about/features/')),
                ('headline', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='trading_app.aboutsection')),
            ],
        ),
        migrations.DeleteModel(
            name='Feature',
        ),
    ]
