# Generated by Django 5.2.5 on 2025-09-03 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading_app', '0015_alter_aboutsection_options_alter_aboutsection_body_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutfeature',
            name='headline',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
