# Generated by Django 5.2.5 on 2025-09-03 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading_app', '0016_alter_aboutfeature_headline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutsection',
            name='kind',
            field=models.CharField(choices=[('hero', 'Hero'), ('who', 'Who We Are'), ('mission', 'Mission'), ('vision', 'Vision'), ('why_choose', 'Why Choose TRACO')], max_length=20),
        ),
    ]
