# Generated by Django 5.2.5 on 2025-09-03 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading_app', '0017_alter_aboutsection_kind'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogIntroSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Main heading before highlighted text', max_length=255)),
                ('highlight_title', models.CharField(help_text='Highlighted text in neon green (e.g. Build Knowledge)', max_length=100)),
                ('description', models.TextField(help_text='Paragraph under the heading')),
                ('highlight_word', models.CharField(help_text='Highlighted word inside description (e.g. TRACO)', max_length=50)),
                ('image', models.ImageField(help_text='Main oval image', upload_to='blog/intro/')),
                ('icon1', models.ImageField(blank=True, help_text='Top-right decorative icon', null=True, upload_to='blog/intro/icons/')),
                ('icon2', models.ImageField(blank=True, help_text='Bottom-left decorative icon', null=True, upload_to='blog/intro/icons/')),
            ],
            options={
                'verbose_name': 'Blog Intro Section',
                'verbose_name_plural': 'Blog Intro Section',
            },
        ),
    ]
