# Generated by Django 5.2.5 on 2025-09-03 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading_app', '0018_blogintrosection'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('meta', models.CharField(help_text="E.g. '5 Mins Read · 20 May 2025'", max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='blogs/')),
                ('category', models.CharField(choices=[('stocks', 'Stocks'), ('mutual-funds', 'Mutual Funds'), ('personal-finance', 'Personal Finance'), ('futures-options', 'Futures & Options')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
