# Generated by Django 5.2.5 on 2025-09-03 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading_app', '0019_blogpost'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunitySection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Build a Strong Community', max_length=150)),
                ('description', models.TextField(default='Join a global network of passionate traders. Share strategies, learn from experts, and grow together in a supportive, success-driven environment.')),
                ('image1', models.ImageField(blank=True, null=True, upload_to='community/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='community/')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='community/')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='community/')),
                ('image5', models.ImageField(blank=True, null=True, upload_to='community/')),
                ('alt1', models.CharField(blank=True, max_length=150, null=True)),
                ('alt2', models.CharField(blank=True, max_length=150, null=True)),
                ('alt3', models.CharField(blank=True, max_length=150, null=True)),
                ('alt4', models.CharField(blank=True, max_length=150, null=True)),
                ('alt5', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'verbose_name': 'Community Section',
                'verbose_name_plural': 'Community Sections',
            },
        ),
    ]
