# Generated by Django 5.2.5 on 2025-09-04 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading_app', '0020_communitysection'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Your Brand', max_length=100)),
                ('logo', models.ImageField(upload_to='dashboard/brand/')),
            ],
        ),
        migrations.CreateModel(
            name='DashboardChart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Account Balance', max_length=120)),
                ('subtitle', models.CharField(default='Monitor Your Account Balance Fluctuation Over Time', max_length=160)),
                ('x_labels', models.JSONField(default=list)),
                ('series1_name', models.CharField(default='Balance', max_length=40)),
                ('series1_data', models.JSONField(default=list)),
                ('series2_name', models.CharField(default='Equity', max_length=40)),
                ('series2_data', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='Gauge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(choices=[('drawdown', 'Drawdown'), ('goals', 'Goals')], max_length=20)),
                ('label', models.CharField(max_length=40)),
                ('percent', models.PositiveSmallIntegerField()),
                ('caption', models.CharField(max_length=80)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['group', 'order'],
            },
        ),
        migrations.CreateModel(
            name='SidebarItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=80)),
                ('href', models.CharField(default='#', max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('icon', models.FileField(upload_to='dashboard/icons/')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SummaryCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('value_prefix', models.CharField(default='$', max_length=5)),
                ('value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('change_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('change_caption', models.CharField(default='This Week', max_length=40)),
                ('icon', models.FileField(upload_to='dashboard/icons/')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ProfileCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('avatar', models.ImageField(upload_to='dashboard/avatars/')),
                ('greeting', models.CharField(default='Hello', max_length=50)),
                ('show_active', models.BooleanField(default=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to='trading_app.brand')),
            ],
        ),
    ]
