# Generated by Django 5.2.5 on 2025-09-04 18:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading_app', '0021_brand_dashboardchart_gauge_sidebaritem_summarycard_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=50)),
                ('change', models.CharField(blank=True, max_length=50, null=True)),
                ('change_type', models.CharField(blank=True, choices=[('success', 'Success'), ('danger', 'Danger'), ('info', 'Info')], max_length=10, null=True)),
                ('note', models.CharField(blank=True, max_length=100, null=True)),
                ('icon', models.ImageField(upload_to='dashboard/icons/')),
            ],
        ),
        migrations.CreateModel(
            name='DashboardUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('account_id', models.CharField(max_length=50)),
                ('status', models.CharField(default='Active', max_length=20)),
                ('evaluation', models.DecimalField(decimal_places=2, max_digits=12)),
                ('profile_image', models.ImageField(upload_to='dashboard/users/')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='dashboard/logo/')),
            ],
        ),
        migrations.CreateModel(
            name='SidebarLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('url', models.CharField(blank=True, max_length=200, null=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='trading_app.sidebarlink')),
            ],
        ),
    ]
