# Generated by Django 5.2.5 on 2025-09-04 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trading_app', '0022_dashboardstat_dashboarduser_sidebarlink'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilecard',
            name='brand',
        ),
        migrations.DeleteModel(
            name='DashboardChart',
        ),
        migrations.DeleteModel(
            name='Gauge',
        ),
        migrations.DeleteModel(
            name='SidebarItem',
        ),
        migrations.RemoveField(
            model_name='sidebarlink',
            name='parent',
        ),
        migrations.DeleteModel(
            name='SummaryCard',
        ),
        migrations.RemoveField(
            model_name='dashboarduser',
            name='account_id',
        ),
        migrations.RemoveField(
            model_name='dashboarduser',
            name='evaluation',
        ),
        migrations.RemoveField(
            model_name='dashboarduser',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='dashboarduser',
            name='status',
        ),
        migrations.DeleteModel(
            name='Brand',
        ),
        migrations.DeleteModel(
            name='ProfileCard',
        ),
        migrations.DeleteModel(
            name='SidebarLink',
        ),
    ]
