# Generated by Django 5.2.5 on 2025-09-04 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading_app', '0023_remove_profilecard_brand_delete_dashboardchart_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboarduser',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='dashboard/logo/'),
        ),
    ]
