# Generated by Django 5.2.5 on 2025-09-05 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading_app', '0025_partnerhero_avatar_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partnerhero',
            name='avatar_text',
        ),
        migrations.AddField(
            model_name='herosection',
            name='avatar_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
